CREATE DATABASE IF NOT EXISTS minor2db;
CREATE USER IF NOT EXISTS 'Aman Agnihotri'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON tasksdb.* TO 'Aman Agnihotri'@'localhost';
FLUSH PRIVILEGES;
USE minor2db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);